give @s[scores={akms=30}] addon:akm_mag_empty
give @s[scores={akms=29}] addon:akm_mag_empty 1 29
give @s[scores={akms=28}] addon:akm_mag_empty 1 28
give @s[scores={akms=27}] addon:akm_mag_empty 1 27
give @s[scores={akms=26}] addon:akm_mag_empty 1 26
give @s[scores={akms=25}] addon:akm_mag_empty 1 25
give @s[scores={akms=24}] addon:akm_mag_empty 1 24
give @s[scores={akms=23}] addon:akm_mag_empty 1 23
give @s[scores={akms=22}] addon:akm_mag_empty 1 22
give @s[scores={akms=21}] addon:akm_mag_empty 1 21
give @s[scores={akms=20}] addon:akm_mag_empty 1 20
give @s[scores={akms=19}] addon:akm_mag_empty 1 19
give @s[scores={akms=18}] addon:akm_mag_empty 1 18
give @s[scores={akms=17}] addon:akm_mag_empty 1 17
give @s[scores={akms=16}] addon:akm_mag_empty 1 16
give @s[scores={akms=15}] addon:akm_mag_empty 1 15
give @s[scores={akms=14}] addon:akm_mag_empty 1 14
give @s[scores={akms=13}] addon:akm_mag_empty 1 13
give @s[scores={akms=12}] addon:akm_mag_empty 1 12
give @s[scores={akms=11}] addon:akm_mag_empty 1 11
give @s[scores={akms=10}] addon:akm_mag_empty 1 10
give @s[scores={akms=9}] addon:akm_mag_empty 1 9
give @s[scores={akms=8}] addon:akm_mag_empty 1 8
give @s[scores={akms=7}] addon:akm_mag_empty 1 7
give @s[scores={akms=6}] addon:akm_mag_empty 1 6
give @s[scores={akms=5}] addon:akm_mag_empty 1 5
give @s[scores={akms=4}] addon:akm_mag_empty 1 4
give @s[scores={akms=3}] addon:akm_mag_empty 1 3
give @s[scores={akms=2}] addon:akm_mag_empty 1 2
give @s[scores={akms=1}] addon:akm_mag_empty 1 1