give @s[scores={pkm=100}] addon:pkm_mag_empty
give @s[scores={pkm=99}] addon:pkm_mag_empty 1 99
give @s[scores={pkm=98}] addon:pkm_mag_empty 1 98
give @s[scores={pkm=97}] addon:pkm_mag_empty 1 97
give @s[scores={pkm=96}] addon:pkm_mag_empty 1 96
give @s[scores={pkm=95}] addon:pkm_mag_empty 1 95
give @s[scores={pkm=94}] addon:pkm_mag_empty 1 94
give @s[scores={pkm=93}] addon:pkm_mag_empty 1 93
give @s[scores={pkm=92}] addon:pkm_mag_empty 1 92
give @s[scores={pkm=91}] addon:pkm_mag_empty 1 91
give @s[scores={pkm=90}] addon:pkm_mag_empty 1 90
give @s[scores={pkm=89}] addon:pkm_mag_empty 1 89
give @s[scores={pkm=88}] addon:pkm_mag_empty 1 88
give @s[scores={pkm=87}] addon:pkm_mag_empty 1 87
give @s[scores={pkm=86}] addon:pkm_mag_empty 1 86
give @s[scores={pkm=85}] addon:pkm_mag_empty 1 85
give @s[scores={pkm=84}] addon:pkm_mag_empty 1 84
give @s[scores={pkm=83}] addon:pkm_mag_empty 1 83
give @s[scores={pkm=82}] addon:pkm_mag_empty 1 82
give @s[scores={pkm=81}] addon:pkm_mag_empty 1 81
give @s[scores={pkm=80}] addon:pkm_mag_empty 1 80
give @s[scores={pkm=79}] addon:pkm_mag_empty 1 79
give @s[scores={pkm=78}] addon:pkm_mag_empty 1 78
give @s[scores={pkm=77}] addon:pkm_mag_empty 1 77
give @s[scores={pkm=76}] addon:pkm_mag_empty 1 76
give @s[scores={pkm=75}] addon:pkm_mag_empty 1 75
give @s[scores={pkm=74}] addon:pkm_mag_empty 1 74
give @s[scores={pkm=73}] addon:pkm_mag_empty 1 73
give @s[scores={pkm=72}] addon:pkm_mag_empty 1 72
give @s[scores={pkm=71}] addon:pkm_mag_empty 1 71
give @s[scores={pkm=70}] addon:pkm_mag_empty 1 70
give @s[scores={pkm=69}] addon:pkm_mag_empty 1 69
give @s[scores={pkm=68}] addon:pkm_mag_empty 1 68
give @s[scores={pkm=67}] addon:pkm_mag_empty 1 67
give @s[scores={pkm=66}] addon:pkm_mag_empty 1 66
give @s[scores={pkm=65}] addon:pkm_mag_empty 1 65
give @s[scores={pkm=64}] addon:pkm_mag_empty 1 64
give @s[scores={pkm=63}] addon:pkm_mag_empty 1 63
give @s[scores={pkm=62}] addon:pkm_mag_empty 1 62
give @s[scores={pkm=61}] addon:pkm_mag_empty 1 61
give @s[scores={pkm=60}] addon:pkm_mag_empty 1 60
give @s[scores={pkm=59}] addon:pkm_mag_empty 1 59
give @s[scores={pkm=58}] addon:pkm_mag_empty 1 58
give @s[scores={pkm=57}] addon:pkm_mag_empty 1 57
give @s[scores={pkm=56}] addon:pkm_mag_empty 1 56
give @s[scores={pkm=55}] addon:pkm_mag_empty 1 55
give @s[scores={pkm=54}] addon:pkm_mag_empty 1 54
give @s[scores={pkm=53}] addon:pkm_mag_empty 1 53
give @s[scores={pkm=52}] addon:pkm_mag_empty 1 52
give @s[scores={pkm=51}] addon:pkm_mag_empty 1 51
give @s[scores={pkm=50}] addon:pkm_mag_empty 1 50
give @s[scores={pkm=49}] addon:pkm_mag_empty 1 49
give @s[scores={pkm=48}] addon:pkm_mag_empty 1 48
give @s[scores={pkm=47}] addon:pkm_mag_empty 1 47
give @s[scores={pkm=46}] addon:pkm_mag_empty 1 46
give @s[scores={pkm=45}] addon:pkm_mag_empty 1 45
give @s[scores={pkm=44}] addon:pkm_mag_empty 1 44
give @s[scores={pkm=43}] addon:pkm_mag_empty 1 43
give @s[scores={pkm=42}] addon:pkm_mag_empty 1 42
give @s[scores={pkm=41}] addon:pkm_mag_empty 1 41
give @s[scores={pkm=40}] addon:pkm_mag_empty 1 40
give @s[scores={pkm=39}] addon:pkm_mag_empty 1 39
give @s[scores={pkm=38}] addon:pkm_mag_empty 1 38
give @s[scores={pkm=37}] addon:pkm_mag_empty 1 37
give @s[scores={pkm=36}] addon:pkm_mag_empty 1 36
give @s[scores={pkm=35}] addon:pkm_mag_empty 1 35
give @s[scores={pkm=34}] addon:pkm_mag_empty 1 34
give @s[scores={pkm=33}] addon:pkm_mag_empty 1 33
give @s[scores={pkm=32}] addon:pkm_mag_empty 1 32
give @s[scores={pkm=31}] addon:pkm_mag_empty 1 31
give @s[scores={pkm=30}] addon:pkm_mag_empty 1 30
give @s[scores={pkm=29}] addon:pkm_mag_empty 1 29
give @s[scores={pkm=28}] addon:pkm_mag_empty 1 28
give @s[scores={pkm=27}] addon:pkm_mag_empty 1 27
give @s[scores={pkm=26}] addon:pkm_mag_empty 1 26
give @s[scores={pkm=25}] addon:pkm_mag_empty 1 25
give @s[scores={pkm=24}] addon:pkm_mag_empty 1 24
give @s[scores={pkm=23}] addon:pkm_mag_empty 1 23
give @s[scores={pkm=22}] addon:pkm_mag_empty 1 22
give @s[scores={pkm=21}] addon:pkm_mag_empty 1 21
give @s[scores={pkm=20}] addon:pkm_mag_empty 1 20
give @s[scores={pkm=19}] addon:pkm_mag_empty 1 19
give @s[scores={pkm=18}] addon:pkm_mag_empty 1 18
give @s[scores={pkm=17}] addon:pkm_mag_empty 1 17
give @s[scores={pkm=16}] addon:pkm_mag_empty 1 16
give @s[scores={pkm=15}] addon:pkm_mag_empty 1 15
give @s[scores={pkm=14}] addon:pkm_mag_empty 1 14
give @s[scores={pkm=13}] addon:pkm_mag_empty 1 13
give @s[scores={pkm=12}] addon:pkm_mag_empty 1 12
give @s[scores={pkm=11}] addon:pkm_mag_empty 1 11
give @s[scores={pkm=10}] addon:pkm_mag_empty 1 10
give @s[scores={pkm=9}] addon:pkm_mag_empty 1 9
give @s[scores={pkm=8}] addon:pkm_mag_empty 1 8
give @s[scores={pkm=7}] addon:pkm_mag_empty 1 7
give @s[scores={pkm=6}] addon:pkm_mag_empty 1 6
give @s[scores={pkm=5}] addon:pkm_mag_empty 1 5
give @s[scores={pkm=4}] addon:pkm_mag_empty 1 4
give @s[scores={pkm=3}] addon:pkm_mag_empty 1 3
give @s[scores={pkm=2}] addon:pkm_mag_empty 1 2
give @s[scores={pkm=1}] addon:pkm_mag_empty 1 1