give @s[scores={pkp_zenit=100}] addon:pkm_mag_empty
give @s[scores={pkp_zenit=99}] addon:pkm_mag_empty 1 99
give @s[scores={pkp_zenit=98}] addon:pkm_mag_empty 1 98
give @s[scores={pkp_zenit=97}] addon:pkm_mag_empty 1 97
give @s[scores={pkp_zenit=96}] addon:pkm_mag_empty 1 96
give @s[scores={pkp_zenit=95}] addon:pkm_mag_empty 1 95
give @s[scores={pkp_zenit=94}] addon:pkm_mag_empty 1 94
give @s[scores={pkp_zenit=93}] addon:pkm_mag_empty 1 93
give @s[scores={pkp_zenit=92}] addon:pkm_mag_empty 1 92
give @s[scores={pkp_zenit=91}] addon:pkm_mag_empty 1 91
give @s[scores={pkp_zenit=90}] addon:pkm_mag_empty 1 90
give @s[scores={pkp_zenit=89}] addon:pkm_mag_empty 1 89
give @s[scores={pkp_zenit=88}] addon:pkm_mag_empty 1 88
give @s[scores={pkp_zenit=87}] addon:pkm_mag_empty 1 87
give @s[scores={pkp_zenit=86}] addon:pkm_mag_empty 1 86
give @s[scores={pkp_zenit=85}] addon:pkm_mag_empty 1 85
give @s[scores={pkp_zenit=84}] addon:pkm_mag_empty 1 84
give @s[scores={pkp_zenit=83}] addon:pkm_mag_empty 1 83
give @s[scores={pkp_zenit=82}] addon:pkm_mag_empty 1 82
give @s[scores={pkp_zenit=81}] addon:pkm_mag_empty 1 81
give @s[scores={pkp_zenit=80}] addon:pkm_mag_empty 1 80
give @s[scores={pkp_zenit=79}] addon:pkm_mag_empty 1 79
give @s[scores={pkp_zenit=78}] addon:pkm_mag_empty 1 78
give @s[scores={pkp_zenit=77}] addon:pkm_mag_empty 1 77
give @s[scores={pkp_zenit=76}] addon:pkm_mag_empty 1 76
give @s[scores={pkp_zenit=75}] addon:pkm_mag_empty 1 75
give @s[scores={pkp_zenit=74}] addon:pkm_mag_empty 1 74
give @s[scores={pkp_zenit=73}] addon:pkm_mag_empty 1 73
give @s[scores={pkp_zenit=72}] addon:pkm_mag_empty 1 72
give @s[scores={pkp_zenit=71}] addon:pkm_mag_empty 1 71
give @s[scores={pkp_zenit=70}] addon:pkm_mag_empty 1 70
give @s[scores={pkp_zenit=69}] addon:pkm_mag_empty 1 69
give @s[scores={pkp_zenit=68}] addon:pkm_mag_empty 1 68
give @s[scores={pkp_zenit=67}] addon:pkm_mag_empty 1 67
give @s[scores={pkp_zenit=66}] addon:pkm_mag_empty 1 66
give @s[scores={pkp_zenit=65}] addon:pkm_mag_empty 1 65
give @s[scores={pkp_zenit=64}] addon:pkm_mag_empty 1 64
give @s[scores={pkp_zenit=63}] addon:pkm_mag_empty 1 63
give @s[scores={pkp_zenit=62}] addon:pkm_mag_empty 1 62
give @s[scores={pkp_zenit=61}] addon:pkm_mag_empty 1 61
give @s[scores={pkp_zenit=60}] addon:pkm_mag_empty 1 60
give @s[scores={pkp_zenit=59}] addon:pkm_mag_empty 1 59
give @s[scores={pkp_zenit=58}] addon:pkm_mag_empty 1 58
give @s[scores={pkp_zenit=57}] addon:pkm_mag_empty 1 57
give @s[scores={pkp_zenit=56}] addon:pkm_mag_empty 1 56
give @s[scores={pkp_zenit=55}] addon:pkm_mag_empty 1 55
give @s[scores={pkp_zenit=54}] addon:pkm_mag_empty 1 54
give @s[scores={pkp_zenit=53}] addon:pkm_mag_empty 1 53
give @s[scores={pkp_zenit=52}] addon:pkm_mag_empty 1 52
give @s[scores={pkp_zenit=51}] addon:pkm_mag_empty 1 51
give @s[scores={pkp_zenit=50}] addon:pkm_mag_empty 1 50
give @s[scores={pkp_zenit=49}] addon:pkm_mag_empty 1 49
give @s[scores={pkp_zenit=48}] addon:pkm_mag_empty 1 48
give @s[scores={pkp_zenit=47}] addon:pkm_mag_empty 1 47
give @s[scores={pkp_zenit=46}] addon:pkm_mag_empty 1 46
give @s[scores={pkp_zenit=45}] addon:pkm_mag_empty 1 45
give @s[scores={pkp_zenit=44}] addon:pkm_mag_empty 1 44
give @s[scores={pkp_zenit=43}] addon:pkm_mag_empty 1 43
give @s[scores={pkp_zenit=42}] addon:pkm_mag_empty 1 42
give @s[scores={pkp_zenit=41}] addon:pkm_mag_empty 1 41
give @s[scores={pkp_zenit=40}] addon:pkm_mag_empty 1 40
give @s[scores={pkp_zenit=39}] addon:pkm_mag_empty 1 39
give @s[scores={pkp_zenit=38}] addon:pkm_mag_empty 1 38
give @s[scores={pkp_zenit=37}] addon:pkm_mag_empty 1 37
give @s[scores={pkp_zenit=36}] addon:pkm_mag_empty 1 36
give @s[scores={pkp_zenit=35}] addon:pkm_mag_empty 1 35
give @s[scores={pkp_zenit=34}] addon:pkm_mag_empty 1 34
give @s[scores={pkp_zenit=33}] addon:pkm_mag_empty 1 33
give @s[scores={pkp_zenit=32}] addon:pkm_mag_empty 1 32
give @s[scores={pkp_zenit=31}] addon:pkm_mag_empty 1 31
give @s[scores={pkp_zenit=30}] addon:pkm_mag_empty 1 30
give @s[scores={pkp_zenit=29}] addon:pkm_mag_empty 1 29
give @s[scores={pkp_zenit=28}] addon:pkm_mag_empty 1 28
give @s[scores={pkp_zenit=27}] addon:pkm_mag_empty 1 27
give @s[scores={pkp_zenit=26}] addon:pkm_mag_empty 1 26
give @s[scores={pkp_zenit=25}] addon:pkm_mag_empty 1 25
give @s[scores={pkp_zenit=24}] addon:pkm_mag_empty 1 24
give @s[scores={pkp_zenit=23}] addon:pkm_mag_empty 1 23
give @s[scores={pkp_zenit=22}] addon:pkm_mag_empty 1 22
give @s[scores={pkp_zenit=21}] addon:pkm_mag_empty 1 21
give @s[scores={pkp_zenit=20}] addon:pkm_mag_empty 1 20
give @s[scores={pkp_zenit=19}] addon:pkm_mag_empty 1 19
give @s[scores={pkp_zenit=18}] addon:pkm_mag_empty 1 18
give @s[scores={pkp_zenit=17}] addon:pkm_mag_empty 1 17
give @s[scores={pkp_zenit=16}] addon:pkm_mag_empty 1 16
give @s[scores={pkp_zenit=15}] addon:pkm_mag_empty 1 15
give @s[scores={pkp_zenit=14}] addon:pkm_mag_empty 1 14
give @s[scores={pkp_zenit=13}] addon:pkm_mag_empty 1 13
give @s[scores={pkp_zenit=12}] addon:pkm_mag_empty 1 12
give @s[scores={pkp_zenit=11}] addon:pkm_mag_empty 1 11
give @s[scores={pkp_zenit=10}] addon:pkm_mag_empty 1 10
give @s[scores={pkp_zenit=9}] addon:pkm_mag_empty 1 9
give @s[scores={pkp_zenit=8}] addon:pkm_mag_empty 1 8
give @s[scores={pkp_zenit=7}] addon:pkm_mag_empty 1 7
give @s[scores={pkp_zenit=6}] addon:pkm_mag_empty 1 6
give @s[scores={pkp_zenit=5}] addon:pkm_mag_empty 1 5
give @s[scores={pkp_zenit=4}] addon:pkm_mag_empty 1 4
give @s[scores={pkp_zenit=3}] addon:pkm_mag_empty 1 3
give @s[scores={pkp_zenit=2}] addon:pkm_mag_empty 1 2
give @s[scores={pkp_zenit=1}] addon:pkm_mag_empty 1 1