give @s[scores={pkp=100}] addon:pkm_mag_empty
give @s[scores={pkp=99}] addon:pkm_mag_empty 1 99
give @s[scores={pkp=98}] addon:pkm_mag_empty 1 98
give @s[scores={pkp=97}] addon:pkm_mag_empty 1 97
give @s[scores={pkp=96}] addon:pkm_mag_empty 1 96
give @s[scores={pkp=95}] addon:pkm_mag_empty 1 95
give @s[scores={pkp=94}] addon:pkm_mag_empty 1 94
give @s[scores={pkp=93}] addon:pkm_mag_empty 1 93
give @s[scores={pkp=92}] addon:pkm_mag_empty 1 92
give @s[scores={pkp=91}] addon:pkm_mag_empty 1 91
give @s[scores={pkp=90}] addon:pkm_mag_empty 1 90
give @s[scores={pkp=89}] addon:pkm_mag_empty 1 89
give @s[scores={pkp=88}] addon:pkm_mag_empty 1 88
give @s[scores={pkp=87}] addon:pkm_mag_empty 1 87
give @s[scores={pkp=86}] addon:pkm_mag_empty 1 86
give @s[scores={pkp=85}] addon:pkm_mag_empty 1 85
give @s[scores={pkp=84}] addon:pkm_mag_empty 1 84
give @s[scores={pkp=83}] addon:pkm_mag_empty 1 83
give @s[scores={pkp=82}] addon:pkm_mag_empty 1 82
give @s[scores={pkp=81}] addon:pkm_mag_empty 1 81
give @s[scores={pkp=80}] addon:pkm_mag_empty 1 80
give @s[scores={pkp=79}] addon:pkm_mag_empty 1 79
give @s[scores={pkp=78}] addon:pkm_mag_empty 1 78
give @s[scores={pkp=77}] addon:pkm_mag_empty 1 77
give @s[scores={pkp=76}] addon:pkm_mag_empty 1 76
give @s[scores={pkp=75}] addon:pkm_mag_empty 1 75
give @s[scores={pkp=74}] addon:pkm_mag_empty 1 74
give @s[scores={pkp=73}] addon:pkm_mag_empty 1 73
give @s[scores={pkp=72}] addon:pkm_mag_empty 1 72
give @s[scores={pkp=71}] addon:pkm_mag_empty 1 71
give @s[scores={pkp=70}] addon:pkm_mag_empty 1 70
give @s[scores={pkp=69}] addon:pkm_mag_empty 1 69
give @s[scores={pkp=68}] addon:pkm_mag_empty 1 68
give @s[scores={pkp=67}] addon:pkm_mag_empty 1 67
give @s[scores={pkp=66}] addon:pkm_mag_empty 1 66
give @s[scores={pkp=65}] addon:pkm_mag_empty 1 65
give @s[scores={pkp=64}] addon:pkm_mag_empty 1 64
give @s[scores={pkp=63}] addon:pkm_mag_empty 1 63
give @s[scores={pkp=62}] addon:pkm_mag_empty 1 62
give @s[scores={pkp=61}] addon:pkm_mag_empty 1 61
give @s[scores={pkp=60}] addon:pkm_mag_empty 1 60
give @s[scores={pkp=59}] addon:pkm_mag_empty 1 59
give @s[scores={pkp=58}] addon:pkm_mag_empty 1 58
give @s[scores={pkp=57}] addon:pkm_mag_empty 1 57
give @s[scores={pkp=56}] addon:pkm_mag_empty 1 56
give @s[scores={pkp=55}] addon:pkm_mag_empty 1 55
give @s[scores={pkp=54}] addon:pkm_mag_empty 1 54
give @s[scores={pkp=53}] addon:pkm_mag_empty 1 53
give @s[scores={pkp=52}] addon:pkm_mag_empty 1 52
give @s[scores={pkp=51}] addon:pkm_mag_empty 1 51
give @s[scores={pkp=50}] addon:pkm_mag_empty 1 50
give @s[scores={pkp=49}] addon:pkm_mag_empty 1 49
give @s[scores={pkp=48}] addon:pkm_mag_empty 1 48
give @s[scores={pkp=47}] addon:pkm_mag_empty 1 47
give @s[scores={pkp=46}] addon:pkm_mag_empty 1 46
give @s[scores={pkp=45}] addon:pkm_mag_empty 1 45
give @s[scores={pkp=44}] addon:pkm_mag_empty 1 44
give @s[scores={pkp=43}] addon:pkm_mag_empty 1 43
give @s[scores={pkp=42}] addon:pkm_mag_empty 1 42
give @s[scores={pkp=41}] addon:pkm_mag_empty 1 41
give @s[scores={pkp=40}] addon:pkm_mag_empty 1 40
give @s[scores={pkp=39}] addon:pkm_mag_empty 1 39
give @s[scores={pkp=38}] addon:pkm_mag_empty 1 38
give @s[scores={pkp=37}] addon:pkm_mag_empty 1 37
give @s[scores={pkp=36}] addon:pkm_mag_empty 1 36
give @s[scores={pkp=35}] addon:pkm_mag_empty 1 35
give @s[scores={pkp=34}] addon:pkm_mag_empty 1 34
give @s[scores={pkp=33}] addon:pkm_mag_empty 1 33
give @s[scores={pkp=32}] addon:pkm_mag_empty 1 32
give @s[scores={pkp=31}] addon:pkm_mag_empty 1 31
give @s[scores={pkp=30}] addon:pkm_mag_empty 1 30
give @s[scores={pkp=29}] addon:pkm_mag_empty 1 29
give @s[scores={pkp=28}] addon:pkm_mag_empty 1 28
give @s[scores={pkp=27}] addon:pkm_mag_empty 1 27
give @s[scores={pkp=26}] addon:pkm_mag_empty 1 26
give @s[scores={pkp=25}] addon:pkm_mag_empty 1 25
give @s[scores={pkp=24}] addon:pkm_mag_empty 1 24
give @s[scores={pkp=23}] addon:pkm_mag_empty 1 23
give @s[scores={pkp=22}] addon:pkm_mag_empty 1 22
give @s[scores={pkp=21}] addon:pkm_mag_empty 1 21
give @s[scores={pkp=20}] addon:pkm_mag_empty 1 20
give @s[scores={pkp=19}] addon:pkm_mag_empty 1 19
give @s[scores={pkp=18}] addon:pkm_mag_empty 1 18
give @s[scores={pkp=17}] addon:pkm_mag_empty 1 17
give @s[scores={pkp=16}] addon:pkm_mag_empty 1 16
give @s[scores={pkp=15}] addon:pkm_mag_empty 1 15
give @s[scores={pkp=14}] addon:pkm_mag_empty 1 14
give @s[scores={pkp=13}] addon:pkm_mag_empty 1 13
give @s[scores={pkp=12}] addon:pkm_mag_empty 1 12
give @s[scores={pkp=11}] addon:pkm_mag_empty 1 11
give @s[scores={pkp=10}] addon:pkm_mag_empty 1 10
give @s[scores={pkp=9}] addon:pkm_mag_empty 1 9
give @s[scores={pkp=8}] addon:pkm_mag_empty 1 8
give @s[scores={pkp=7}] addon:pkm_mag_empty 1 7
give @s[scores={pkp=6}] addon:pkm_mag_empty 1 6
give @s[scores={pkp=5}] addon:pkm_mag_empty 1 5
give @s[scores={pkp=4}] addon:pkm_mag_empty 1 4
give @s[scores={pkp=3}] addon:pkm_mag_empty 1 3
give @s[scores={pkp=2}] addon:pkm_mag_empty 1 2
give @s[scores={pkp=1}] addon:pkm_mag_empty 1 1