give @s[scores={rpk=75}] addon:rpk_mag_empty
give @s[scores={rpk=74}] addon:rpk_mag_empty 1 74
give @s[scores={rpk=73}] addon:rpk_mag_empty 1 73
give @s[scores={rpk=72}] addon:rpk_mag_empty 1 72
give @s[scores={rpk=71}] addon:rpk_mag_empty 1 71
give @s[scores={rpk=70}] addon:rpk_mag_empty 1 70
give @s[scores={rpk=69}] addon:rpk_mag_empty 1 69
give @s[scores={rpk=68}] addon:rpk_mag_empty 1 68
give @s[scores={rpk=67}] addon:rpk_mag_empty 1 67
give @s[scores={rpk=66}] addon:rpk_mag_empty 1 66
give @s[scores={rpk=65}] addon:rpk_mag_empty 1 65
give @s[scores={rpk=64}] addon:rpk_mag_empty 1 64
give @s[scores={rpk=63}] addon:rpk_mag_empty 1 63
give @s[scores={rpk=62}] addon:rpk_mag_empty 1 62
give @s[scores={rpk=61}] addon:rpk_mag_empty 1 61
give @s[scores={rpk=60}] addon:rpk_mag_empty 1 60
give @s[scores={rpk=59}] addon:rpk_mag_empty 1 59
give @s[scores={rpk=58}] addon:rpk_mag_empty 1 58
give @s[scores={rpk=57}] addon:rpk_mag_empty 1 57
give @s[scores={rpk=56}] addon:rpk_mag_empty 1 56
give @s[scores={rpk=55}] addon:rpk_mag_empty 1 55
give @s[scores={rpk=54}] addon:rpk_mag_empty 1 54
give @s[scores={rpk=53}] addon:rpk_mag_empty 1 53
give @s[scores={rpk=52}] addon:rpk_mag_empty 1 52
give @s[scores={rpk=51}] addon:rpk_mag_empty 1 51
give @s[scores={rpk=50}] addon:rpk_mag_empty 1 50
give @s[scores={rpk=49}] addon:rpk_mag_empty 1 49
give @s[scores={rpk=48}] addon:rpk_mag_empty 1 48
give @s[scores={rpk=47}] addon:rpk_mag_empty 1 47
give @s[scores={rpk=46}] addon:rpk_mag_empty 1 46
give @s[scores={rpk=45}] addon:rpk_mag_empty 1 45
give @s[scores={rpk=44}] addon:rpk_mag_empty 1 44
give @s[scores={rpk=43}] addon:rpk_mag_empty 1 43
give @s[scores={rpk=42}] addon:rpk_mag_empty 1 42
give @s[scores={rpk=41}] addon:rpk_mag_empty 1 41
give @s[scores={rpk=40}] addon:rpk_mag_empty 1 40
give @s[scores={rpk=39}] addon:rpk_mag_empty 1 39
give @s[scores={rpk=38}] addon:rpk_mag_empty 1 38
give @s[scores={rpk=37}] addon:rpk_mag_empty 1 37
give @s[scores={rpk=36}] addon:rpk_mag_empty 1 36
give @s[scores={rpk=35}] addon:rpk_mag_empty 1 35
give @s[scores={rpk=34}] addon:rpk_mag_empty 1 34
give @s[scores={rpk=33}] addon:rpk_mag_empty 1 33
give @s[scores={rpk=32}] addon:rpk_mag_empty 1 32
give @s[scores={rpk=31}] addon:rpk_mag_empty 1 31
give @s[scores={rpk=30}] addon:rpk_mag_empty 1 30
give @s[scores={rpk=29}] addon:rpk_mag_empty 1 29
give @s[scores={rpk=28}] addon:rpk_mag_empty 1 28
give @s[scores={rpk=27}] addon:rpk_mag_empty 1 27
give @s[scores={rpk=26}] addon:rpk_mag_empty 1 26
give @s[scores={rpk=25}] addon:rpk_mag_empty 1 25
give @s[scores={rpk=24}] addon:rpk_mag_empty 1 24
give @s[scores={rpk=23}] addon:rpk_mag_empty 1 23
give @s[scores={rpk=22}] addon:rpk_mag_empty 1 22
give @s[scores={rpk=21}] addon:rpk_mag_empty 1 21
give @s[scores={rpk=20}] addon:rpk_mag_empty 1 20
give @s[scores={rpk=19}] addon:rpk_mag_empty 1 19
give @s[scores={rpk=18}] addon:rpk_mag_empty 1 18
give @s[scores={rpk=17}] addon:rpk_mag_empty 1 17
give @s[scores={rpk=16}] addon:rpk_mag_empty 1 16
give @s[scores={rpk=15}] addon:rpk_mag_empty 1 15
give @s[scores={rpk=14}] addon:rpk_mag_empty 1 14
give @s[scores={rpk=13}] addon:rpk_mag_empty 1 13
give @s[scores={rpk=12}] addon:rpk_mag_empty 1 12
give @s[scores={rpk=11}] addon:rpk_mag_empty 1 11
give @s[scores={rpk=10}] addon:rpk_mag_empty 1 10
give @s[scores={rpk=9}] addon:rpk_mag_empty 1 9
give @s[scores={rpk=8}] addon:rpk_mag_empty 1 8
give @s[scores={rpk=7}] addon:rpk_mag_empty 1 7
give @s[scores={rpk=6}] addon:rpk_mag_empty 1 6
give @s[scores={rpk=5}] addon:rpk_mag_empty 1 5
give @s[scores={rpk=4}] addon:rpk_mag_empty 1 4
give @s[scores={rpk=3}] addon:rpk_mag_empty 1 3
give @s[scores={rpk=2}] addon:rpk_mag_empty 1 2
give @s[scores={rpk=1}] addon:rpk_mag_empty 1 1